# Generated by Django 6.0.6 on 2026-07-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('prenom', models.CharField(max_length=25)),
                ('entreprise_label', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.IntegerField()),
                ('adress', models.CharField()),
                ('num_employe', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rendezvous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField()),
                ('date_time', models.DateTimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
    ]
