# Generated by Django 6.0.6 on 2026-07-08 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_categorie_prospect_rendezvous'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prospect',
            old_name='entreprise_label',
            new_name='enterprise_label',
        ),
    ]
