# Generated by Django 6.0.6 on 2026-07-08 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_rename_entreprise_label_prospect_enterprise_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prospect',
            old_name='prenom',
            new_name='lastname',
        ),
    ]
