# Generated by Django 6.0.6 on 2026-07-09 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_rename_prenom_prospect_lastname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='frame_img',
        ),
        migrations.RemoveField(
            model_name='prospect',
            name='adress',
        ),
        migrations.RemoveField(
            model_name='prospect',
            name='email',
        ),
        migrations.RemoveField(
            model_name='prospect',
            name='num_employe',
        ),
        migrations.RemoveField(
            model_name='prospect',
            name='telephone',
        ),
        migrations.RemoveField(
            model_name='rendezvous',
            name='end_time',
        ),
        migrations.AddField(
            model_name='prospect',
            name='status',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('annule', 'Annulé')], default='en_attente', max_length=20),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='prospect',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='website.prospect'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categorie',
            name='designation',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='designation',
            field=models.CharField(max_length=100),
        ),
    ]
