# Generated by Django 6.0.6 on 2026-07-09 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_delete_frame_img_remove_prospect_adress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('confirme', 'Confirmé'), ('terminee', 'Terminé')], default='en_attente', max_length=20),
        ),
    ]
