# Generated by Django 6.0.6 on 2026-07-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_rendezvous_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prospect',
            name='tel',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('confirme', 'Confirmé'), ('annule', 'Annulé'), ('reporte', 'Reporté'), ('terminee', 'Terminé')], default='en_attente', max_length=20),
        ),
    ]
