# Generated by Django 6.0.6 on 2026-07-14 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_prospect_email_prospect_tel_alter_rendezvous_statut'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
    ]
