# Generated by Django 6.0.6 on 2026-07-14 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='site_web',
            field=models.URLField(blank=True, null=True),
        ),
    ]
