# Generated by Django 6.0.6 on 2026-07-17 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_commentaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='taille_entreprise',
            field=models.CharField(choices=[('1-5', '1 à 5 employés'), ('6-20', '6 à 20 employés'), ('21-50', '21 à 50 employés'), ('50+', 'Plus de 50 employés')], default='1-5', max_length=10),
        ),
    ]
