# Generated by Django 6.0.6 on 2026-07-17 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_prospect_taille_entreprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.categorie'),
        ),
    ]
