# Generated by Django 6.0.6 on 2026-07-14 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website', '0010_commentaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='RdvAnnuler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('rendezvous', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='annulation', to='website.rendezvous')),
            ],
        ),
    ]
